project:
  name: "pre-push"
  modules: ["pre-push"]
  bin: "bin"

actions:
  - name: version-check
    run: |
      echo "Checking version: ${{ tag }}"
      if [ -z "${{ tag }}" ]; then
        echo "No version tag found"
        exit 1
      fi
      echo "Version check passed: ${{ tag }}"

  - name: version-greatest
    run: |
      echo "Checking if ${{ tag }} is the greatest version"
      # This would normally call the version tool
      echo "Version greatest check passed"

  - name: version-module
    run: |
      for module in $(scripts/version modules); do
        echo "Checking module: bin/$module"
        module_version=$(bin/$module -V 2>/dev/null || echo "")
        if [ -z "$module_version" ]; then
          echo "Could not get version from bin/$module -V"
          exit 1
        fi
        if [ "$module_version" != "${{ tag }}" ]; then
          echo "Version mismatch: bin/$module reports $module_version, expected ${{ tag }}"
          echo "To check manually run: bin/$module -V"
          exit 1
        fi
        echo "✓ bin/$module version matches: $module_version"
      done

  - name: run-tests
    run: go test ./... -v -race

  - name: git-untracked
    uses: git@untracked

  - name: git-uncommitted
    uses: git@uncommitted

  - name: git-modified
    uses: git@modified

stages:
  pre-push:
    steps:
      - action: version-check
      - action: version-greatest

      # Always run version module validation
      - action: version-module
      
      # Run tests only for release versions
      - action: run-tests
        only: [release]
        require: [version-module]
      
      # Run Git checks for all versions      
      - action: git-untracked
      - action: git-uncommitted
      - action: git-modified
        onerror: warn